[Scheme]
Name=X-ACS dark
ColorForeground=#eeeeeeeeeeee
ColorBackground=#220022002255
TabActivityColor=#ffff22222222
ColorCursorUseDefault=FALSE
ColorCursor=#bbbbbbbbbbbb
ColorCursorForeground=#1166116611dd
ColorSelectionUseDefault=TRUE
ColorSelection=#eeeeeeeeeeee
ColorSelectionBackground=#444444444444
ColorPalette=#111111;#ff2222;#00dd55;#ffbb11;#1166ff;#dd33ff;#00ccee;#bbbbbb;#444444;#ff5050;#7cff6d;#ffdc6d;#7391ff;#f287f2;#53c7ff;#eeeeee
ColorBoldIsBright=TRUE